spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:clipdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-ui
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  security:
    user:
      name: clip
      password: clip-pass